project:
  type: website
  output-dir: docs # docs is the folder name Github Pages uses

website:
  title: "Anne-Céline Granjon, PhD"
  description: "This is a professional personal page"
  navbar:
    background: primary # Primary, secondary and tertiary are colour name shortcuts
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: My CV
      - href: publications.qmd # If `text` is not provided, the `title` of the page will be shown
        text: Publications
    tools:
      - icon: github
        menu:
          - text: Website Code
            href: https://github.com/acgranjon/acgranjon.github.io/
          - text: My repositories
            href: https://github.com/acgranjon/

format:
  html:
    theme: lux
      # light: lux
      # dark: cyborg
    css: styles.css
    toc: true

editor: source # with quarto and Rstudio, you can also use a `visual` editor WYSIWYG
